name: Release

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'davitp/mirocli'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Install jq
        uses: dcarbone/install-jq-action@v3.0.1

      - name: Extract Next Version
        id: version
        run: |
          NEXT_VERSION=$(npx semantic-release --dry-run --no-ci | grep 'nextRelease:' | grep -oP '(?<=version: )[^,}]+')
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update package.json with version
        run: |
          jq '.version = "$NEXT_VERSION"' package.json > temp.json && mv temp.json package.json
        env:
          NEXT_VERSION: ${{ env.NEXT_VERSION }}

      - name: Build
        run: pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
